### ISSUE TITLE
App no longer updating

### ISSUE THREAD

**Issue by vincer** [finiteloop/air-quality#8]
Last update was 4 days ago. Hitting refresh does nothing.
![5ABF4FDF-9C4D-4063-A03A-03F0EDCFF46B](https://user-images.githubusercontent.com/792368/102019259-61471780-3d27-11eb-8513-f76145ad8023.png)

**Comment by finiteloop** [comment]
Thank you, I noticed the same thing. PurpleAir seems to have discontinued its JSON data service:

https://www.purpleair.com/json

I just sent them an email to inquire what is going on. I will keep you posted as soon as I hear back!

**Comment by vincer** [comment]
Looks like they've updated their API recently.

https://www.reddit.com/r/PurpleAir/comments/jw3mn3/purpleair_json_api_changed_or_just_down/
https://api.purpleair.com

Now they require API keys and such (though I don't see how to get a key...). Makes sense as I imagine the usage has gone through the roof in the past few months.

Thanks for the app, btw. Super useful.

**Comment by finiteloop** [comment]
Finally got an API key from PurpleAir support! Will fix tomorrow

**Comment by finiteloop** [comment]
Fixed and pushed with https://github.com/finiteloop/air-quality/commit/37b610111d530afebb31c1f1aadc4a6f40991797
